// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyChurch.Web.Data;

namespace MyChurch.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200220165717_CompletDB")]
    partial class CompletDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyChurch.Web.Data.Entities.ChurchEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate");

                    b.Property<bool>("IsActive");

                    b.Property<int?>("MentorId");

                    b.Property<int?>("MinistryId");

                    b.Property<decimal>("Price");

                    b.Property<string>("Remarks")
                        .IsRequired();

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.HasIndex("MinistryId");

                    b.ToTable("ChurchEvents");
                });

            modelBuilder.Entity("MyChurch.Web.Data.Entities.Disciple", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(100);

                    b.Property<string>("CellPhone")
                        .HasMaxLength(20);

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("FixedPhone")
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Disciples");
                });

            modelBuilder.Entity("MyChurch.Web.Data.Entities.MemberImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DiscipleId");

                    b.Property<string>("ImageUrl")
                        .IsRequired();

                    b.Property<int?>("MentorId");

                    b.HasKey("Id");

                    b.HasIndex("DiscipleId");

                    b.HasIndex("MentorId");

                    b.ToTable("MemberImages");
                });

            modelBuilder.Entity("MyChurch.Web.Data.Entities.Mentor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(100);

                    b.Property<string>("CellPhone")
                        .HasMaxLength(20);

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("FixedPhone")
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("MyChurch.Web.Data.Entities.Ministry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BiblicalWord");

                    b.Property<int?>("DiscipleId");

                    b.Property<decimal>("Fund");

                    b.Property<bool>("IsAvailable");

                    b.Property<string>("Leader")
                        .IsRequired();

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("MeetEndDate");

                    b.Property<DateTime>("MeetStartDate");

                    b.Property<int?>("MentorId");

                    b.Property<int?>("MinistryImageId");

                    b.Property<int?>("MinistryTypeId");

                    b.Property<string>("Remark");

                    b.Property<string>("SubLeader")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("DiscipleId");

                    b.HasIndex("MentorId");

                    b.HasIndex("MinistryImageId");

                    b.HasIndex("MinistryTypeId");

                    b.ToTable("Ministries");
                });

            modelBuilder.Entity("MyChurch.Web.Data.Entities.MinistryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("MinistryImages");
                });

            modelBuilder.Entity("MyChurch.Web.Data.Entities.MinistryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("MinistryTypes");
                });

            modelBuilder.Entity("MyChurch.Web.Data.Entities.ChurchEvent", b =>
                {
                    b.HasOne("MyChurch.Web.Data.Entities.Mentor", "Mentor")
                        .WithMany("ChurchEvents")
                        .HasForeignKey("MentorId");

                    b.HasOne("MyChurch.Web.Data.Entities.Ministry", "Ministry")
                        .WithMany("ChurchEvents")
                        .HasForeignKey("MinistryId");
                });

            modelBuilder.Entity("MyChurch.Web.Data.Entities.MemberImage", b =>
                {
                    b.HasOne("MyChurch.Web.Data.Entities.Disciple", "Disciple")
                        .WithMany("MemberImages")
                        .HasForeignKey("DiscipleId");

                    b.HasOne("MyChurch.Web.Data.Entities.Mentor", "Mentor")
                        .WithMany("MemberImages")
                        .HasForeignKey("MentorId");
                });

            modelBuilder.Entity("MyChurch.Web.Data.Entities.Ministry", b =>
                {
                    b.HasOne("MyChurch.Web.Data.Entities.Disciple", "Disciple")
                        .WithMany("Ministries")
                        .HasForeignKey("DiscipleId");

                    b.HasOne("MyChurch.Web.Data.Entities.Mentor", "Mentor")
                        .WithMany("Ministries")
                        .HasForeignKey("MentorId");

                    b.HasOne("MyChurch.Web.Data.Entities.MinistryImage", "MinistryImage")
                        .WithMany("Ministries")
                        .HasForeignKey("MinistryImageId");

                    b.HasOne("MyChurch.Web.Data.Entities.MinistryType", "MinistryType")
                        .WithMany("Ministries")
                        .HasForeignKey("MinistryTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
